#ifndef DEVA_FRAMEWORK_CORE_SERIALIZATION_BINARY_CONFIG_HPP
#define DEVA_FRAMEWORK_CORE_SERIALIZATION_BINARY_CONFIG_HPP

#include "../Config.hpp"

#include "../Serializable.hpp"

namespace DevaFramework {

}

#endif //DEVA_FRAMEWORK_CORE_SERIALIZATION_BINARY_CONFIG_HPP