#ifndef DEVA_FRAMEWORK_WINDOW_INPUT_INPUT_DEVICE_HPP
#define DEVA_FRAMEWORK_WINDOW_INPUT_INPUT_DEVICE_HPP

#include "Config.hpp"

namespace DevaFramework
{
}

#endif //DEVA_FRAMEWORK_WINDOW_INPUT_INPUT_DEVICE_HPP