language: c++
sudo: required
install:
 - sudo apt-get install build-essential
 - pwd
 - mkdir cmake
 - cd cmake
 - wget --no-check-certificate https://cmake.org/files/v3.6/cmake-3.6.0-rc2-Linux-x86_64.tar.gz
 - tar xf cmake-3.6.0-rc2-Linux-x86_64.tar.gz -C .
 - ls
 - cd ..
script: 
- pwd
- mkdir build
- cd build
- ../cmake/cmake-3.6.0-rc2-Linux-x86_64/bin/cmake ..
- make deva-Framework
- make deva-Engine
- make test-all
notifications:
  email:
    on_success: always
    on_failure: never