language: c++
sudo: required
install:
- sudo apt-get install software-properties-common
- sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
- sudo apt-get update
- sudo apt-get upgrade
script: 
- mkdir build
- cd build
- cmake ..
- make Deva
- make test-all
notifications:
  email:
    on_success: always
    on_failure: never