language: c++
sudo: required
addons:
    apt:
      sourceline: 'ppa:george-edison55/cmake-3.x'
      packages: ['cmake']
script: 
- mkdir build
- cd build
- cmake ..
- make Deva
- make test-all
notifications:
  email:
    on_success: always
    on_failure: never