language: c++
install:
- sudo:required
- apt-get install software-properties-common
- add-apt-repository ppa:george-edison55/cmake-3.x
- apt-get update
- apt-get upgrade
script: 
- mkdir build
- cd build
- cmake ..
- make Deva
- make test-all
notifications:
  email:
    on_success: always
    on_failure: never