language: c++
sudo: required
install:
 - sudo apt-get install build-essential
 - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
 - tar xf cmake-3.2.2.tar.gz
 - cd cmake-3.2.2
 - ./configure
 - sudo make install
script: 
- mkdir build
- cd build
- cmake ..
- make Deva
- make test-all
notifications:
  email:
    on_success: always
    on_failure: never