#ifndef DEVA_FRAMEWORK_GRAPHICS_SHADER_VARIABLE_FACTORY
#define DEVA_FRAMEWORK_GRAPHICS_SHADER_VARIABLE_FACTORY

#include "Config.hpp"

namespace DevaFramework
{
	DEVA_FRAMEWORK_API static ShaderVariableDataType_Integer construct(int i);
}


#endif //DEVA_FRAMEWORK_GRAPHICS_SHADER_VARIABLE_FACTORY