set(
	DEVA_ENGINE_PUBLIC_HEADERS
	${CURDIR}/Graphics/Camera.hpp
	${CURDIR}/Graphics/Config.hpp
	${CURDIR}/Graphics/DrawableObject.cpp
	${CURDIR}/Graphics/DrawableObject.hpp
	${CURDIR}/Graphics/DrawableObjectBuilder.hpp
	${CURDIR}/Graphics/Model.hpp
	${CURDIR}/Graphics/RenderAPI.hpp
	${CURDIR}/Graphics/Renderer.cpp
	${CURDIR}/Graphics/Renderer.hpp
	${CURDIR}/Graphics/RenderSurface.hpp
	${CURDIR}/Graphics/ResourceCache.hpp
	${CURDIR}/Graphics/Scene.cpp
	${CURDIR}/Graphics/Scene.hpp
	${CURDIR}/Graphics/SceneBuilder.cpp
	${CURDIR}/Graphics/SceneBuilder.hpp
	${CURDIR}/Graphics/SceneObject.cpp
	${CURDIR}/Graphics/SceneObject.hpp
	${CURDIR}/Graphics/ScreenRenderer.hpp
	${CURDIR}/Graphics/GUI/Component.hpp
	${CURDIR}/Graphics/Vulkan/Config.hpp
	${CURDIR}/Graphics/Vulkan/DescriptorPoolManager.cpp
	${CURDIR}/Graphics/Vulkan/DescriptorPoolManager.hpp
	${CURDIR}/Graphics/Vulkan/VulkanBufferMemoryIndex.cpp
	${CURDIR}/Graphics/Vulkan/VulkanBufferMemoryIndex.hpp
	${CURDIR}/Graphics/Vulkan/VulkanGraphicsPipeline.cpp
	${CURDIR}/Graphics/Vulkan/VulkanPipeline.hpp
	${CURDIR}/Graphics/Vulkan/VulkanPipelineBuilder.cpp
	${CURDIR}/Graphics/Vulkan/VulkanPipelineBuilder.hpp
	${CURDIR}/Graphics/Vulkan/VulkanPresenter.hpp
	${CURDIR}/Graphics/Vulkan/VulkanQueueSubmitBuffer.cpp
	${CURDIR}/Graphics/Vulkan/VulkanQueueSubmitBuffer.hpp
	${CURDIR}/Graphics/Vulkan/VulkanRenderAPI.cpp
	${CURDIR}/Graphics/Vulkan/VulkanRenderAPI.hpp
	${CURDIR}/Graphics/Vulkan/VulkanRenderObject.cpp
	${CURDIR}/Graphics/Vulkan/VulkanRenderObject.hpp
	${CURDIR}/Graphics/Vulkan/VulkanRenderPass.cpp
	${CURDIR}/Graphics/Vulkan/VulkanSwapchain.cpp
	${CURDIR}/Graphics/Vulkan/VulkanSwapchain.hpp
	${CURDIR}/Input/Config.hpp
	${CURDIR}/Input/InputFunction.cpp
	${CURDIR}/Input/InputFunction.hpp
	${CURDIR}/Input/InputListener.cpp
	${CURDIR}/Input/InputListener.hpp
	${CURDIR}/Input/KeyboardListener.cpp
	${CURDIR}/Input/KeyboardListener.hpp
	${CURDIR}/Input/MouseListener.hpp
	${CURDIR}/MinecraftClone/Block.cpp
	${CURDIR}/MinecraftClone/Block.hpp
	${CURDIR}/Config.hpp
	${CURDIR}/DevaEngineInstance.cpp
	${CURDIR}/DevaEngineInstance.hpp
	${CURDIR}/Init.cpp
	${CURDIR}/Init.hpp
	${CURDIR}/Keymap.hpp
	${CURDIR}/Perspective.hpp
	${CURDIR}/Preferences.hpp
	${CURDIR}/Shape.hpp
)