#ifndef DEVA_FRAMEWORK_GRAPHICS_INIT_H
#define DEVA_FRAMEWORK_GRAPHICS_INIT_H

#include "Config.hpp"

namespace DevaFramework {
	DEVA_FRAMEWORK_API int DEVA_INIT_GRAPHICS();
}

#endif //DEVA_FRAMEWORK_GRAPHICS_MAIN_H