#ifndef DEVA_FRAMEWORK_GRAPHICS_IMAGE_READERS_H
#define DEVA_FRAMEWORK_GRAPHICS_IMAGE_READERS_H

#include "Config.hpp"

namespace DevaFramework
{


}

#endif // DEVA_FRAMEWORK_GRAPHICS_IMAGES_IMAGE_READERS_H
