#ifndef DEVA_FRAMEWORK_CORE_SERIALIZATION_CONFIG_HPP
#define DEVA_FRAMEWORK_CORE_SERIALIZATION_CONFIG_HPP

#include "../Config.hpp"

namespace DevaFramework {

	

}

#endif DEVA_FRAMEWORK_CORE_SERIALIZATION_CONFIG_HPP